### PR TITLE
Add script to collect energy vectors from B&W share table

### LINKED ISSUE #2: Add script to get mimo parameters
Add script to get inputs and outputs for processes from csv for sql database

### PR DESCRIPTION
**Pull request by chrwm**
Closes #2 

Add a script to collect the input and output energy vectors for the processes from cloud.

- [x] transfrom user table to 5 database tables
- [x] check if user energy vectors exist in energy vector list
- [x] check naming conventions and energy vector seperator
- [x] export to sqlite db

### CODE REVIEW

**Review by henhuy — CHANGES_REQUESTED** [review]
Thanks for implementing this feature. 
Two small things:
- I would suggest better parameter names (instead of `inp`, `inpu` and `input` - the latter also overwrites pythons internal `input` interface) 
- Could you turn script into function which takes the path to the 2 files and an DB engine as parameters? We can add CLI or script additionally.

After those changes I could add your feature!

**Comment by henhuy** [comment]
One more question:
I thought you would read inputs and parameters from Excel on BWShare directly (not from intermediate step, including two CSVs which have to be preprocessed beforehand). Why you decided against it?

**Comment by henhuy** [comment]
One more thing: 
Could you activate pre-commit on your side - this would remove linter errors on my side! thx

**Comment by henhuy** [comment]
One more review request: Could you move input and mimo CSVs into test_data folder and create test for your new function/script?

**Comment by chrwm** [comment]
Change of plans: 
Idea of five database tables to store the inputs & outputs of process parameters will be scraped.
Instead the user-in_out_process_parameter table will be taken as is and uploaded to OEP.
From the user-in_out_process_parameter table a josn will be created to hand over to the user as modelling information.

**Comment by henhuy** [comment]
> From the user-in_out_process_parameter table a josn will be created to hand over to the user as modelling information.

You must not extract to JSON, but return simple dict from `get_energy_structure`

**Comment by chrwm** [comment]
> > From the user-in_out_process_parameter table a josn will be created to hand over to the user as modelling information.
> 
> You must not extract to JSON, but return simple dict from `get_energy_structure`

Dict in form of this [JSON](https://github.com/sedos-project/data_adapter/blob/dev/collections/hack-a-thon/HARDCODED_ES_STRUCT.json)

**Comment by chrwm** [comment]
Function `get_energy_structure` returns dict with ES_STRUCTURE in form of HARDCODED_ES_STRUCTURE.json. 
I added a test.

**Comment by chrwm** [comment]
What should the default case for "no entries" in the input and output columns be?
Currently the case is not handled yet.
A)
```
{"test_process": {"parameter": {"inputs": [""], "outputs": ["out5"]}}}
```
B)
```
{"test_process": {"parameter": {"inputs": [], "outputs": ["out5"]}}}
```
C) 
```
{"test_process": {"parameter": {"outputs": ["out5"]}}}
```

**Comment by henhuy** [comment]
> What should the default case for "no entries" in the input and output columns be?

B! (thanks for asking)

**Comment by chrwm** [comment]
I implemented the default case for empty inputs and outputs.
In case of `input = lauf Wasser, coal, sonnen Schein` will be converted to
`"inputs": ["laufWasser", "coal", "sonnenSchein"]`

So the spaces will be removed. Do you think that's probematic?

I could change the code to output: `"inputs": ["lauf Wasser", "coal", "sonnen Schein"]`
Not sure if the space will produce further problems down the line.

**Comment by henhuy** [comment]
People should not use spaces within variable names.
So an error message will occur if bus/process cannot be found.
That's okay!

**Comment by chrwm** [comment]
> People should not use spaces within variable names.

This has been communicated.

Feel free to adapt the code during the review. I can't look into it the next week. Also feel free to merge.

**Pull request closed without merging**
