### PR TITLE
Feature/update unit conversion

### PR DESCRIPTION
**Pull request by yechenyan**
Gemäß den im Excel-SEDOS_Modellstruktur angegebenen recommended unit wurden in der Datei unit-conversion.py die entsprechenden Einheiten ergänzt.

### CODE REVIEW

**Comment by henhuy** [comment]
Thanks for implementing recommended units!
I added a small unit conversion test - maybe you could check for some other units as well?
I think we will need some more units - but I or sabine will come to you with further instructions.
Thanks!

**Comment by yechenyan** [comment]
> Thanks for implementing recommended units! I added a small unit conversion test - maybe you could check for some other units as well? I think we will need some more units - but I or sabine will come to you with further instructions. Thanks!

Thank you for providing the test examples. 
I have already added the test code. 
Thanks!

**Review by SabineHaas — CHANGES_REQUESTED** [review]
Looks good to me.
You could use `pytest.approx(1000)` instead of `1000.0000000000001` etc. 
https://docs.pytest.org/en/7.1.x/reference/reference.html#pytest-approx

@henhuy I wonder whether we need an exception for leap years?

**Review by SabineHaas — APPROVED** [review]
Thank you :) Approved from my side.

**Pull request merged**
